DROP DATABASE IF EXISTS Think_a_bitDB;
CREATE DATABASE Think_a_bitDB CHARACTER SET utf8 COLLATE utf8_general_ci;
USE Think_a_bitDB;

CREATE TABLE Eventt (
  Id INTEGER NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
  Title VARCHAR(64) NOT NULL,
  TypeOf ENUM('TASK', 'REMINDER', 'GOAL') NOT NULL DEFAULT 'TASK',
  Location TEXT DEFAULT NULL,
  TimeOf TIMESTAMP NULL,
  Description TEXT DEFAULT NULL,
  AllDay BOOLEAN NOT NULL DEFAULT FALSE,
  Duration INTEGER NULL,
  Reminder INTEGER NOT NULL DEFAULT 0,
  ToRepeat ENUM('NONE', 'DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY') NOT NULL DEFAULT 'NONE'
);

CREATE TABLE User (
  Id INTEGER NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
  UserName VARCHAR(128) NOT NULL,
  Email VARCHAR(64) DEFAULT NULL,
  Password TEXT NOT NULL
);

CREATE TABLE Calendar (
  Id INTEGER NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
  Day TINYINT NOT NULL DEFAULT 1,
  Month TINYINT NOT NULL DEFAULT 1,
  Year SMALLINT NOT NULL DEFAULT 1970
);

CREATE TABLE CalendarEvents (
  EventId INTEGER NOT NULL,
  CalendarId INTEGER NOT NULL,
  FOREIGN KEY (EventId) REFERENCES Eventt(Id),
  FOREIGN KEY (CalendarId) REFERENCES Calendar(Id),
  PRIMARY KEY(EventId, CalendarId)
);
-- will add UserId to this table later
