DROP DATABASE IF EXISTS sql7263770;
ALTER DATABASE sql7263770 CHARACTER SET utf8 COLLATE utf8_general_ci;
USE sql7263770;

CREATE TABLE Eventt (
  Id INTEGER NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
  Title VARCHAR(64) NOT NULL,
  TypeOf ENUM('TASK', 'REMINDER', 'GOAL') NOT NULL DEFAULT 'TASK',
  Location TEXT DEFAULT NULL,
  TimeOf TIMESTAMP NULL,
  Description TEXT DEFAULT NULL,
  AllDay BOOLEAN NOT NULL DEFAULT FALSE,
  Duration INTEGER NULL,
  Reminder INTEGER NOT NULL DEFAULT 0,
  ToRepeat ENUM('NONE', 'DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY') NOT NULL DEFAULT 'NONE'
);

CREATE TABLE CalendarEvents (
  Id INTEGER NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
  EventId INTEGER NOT NULL,
  Date DATE NOT NULL,
  FOREIGN KEY (EventId) REFERENCES Eventt(Id) ON UPDATE CASCADE ON DELETE CASCADE
);
